GET http://localhost:8080/api/user/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsIm5hbWUiOiJNYXJrIExvd2llIEFuZ2VsZXMiLCJ1c2VybmFtZSI6Imx1aTAzMjIiLCJ1c2VyX3JvbGUiOiIyIiwiZW1haWwiOiJtYXJrQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHdVY3JscXZiM29tSFl4cHdwZVhJamVmMUxrT21tTThDajIuSTI0RW1hZXRRYkpDdjJFMmsuIiwiY3JlYXRlZCI6IjIwMjAtMDgtMDVUMDg6NDI6MjUuMDAwWiIsImlhdCI6MTU5NjYxNjk1MiwiZXhwIjoxNTk2NjI0MTUyfQ.7WC4HpYe0v2UdvHHhbhK6rtx77AX-XjY9Gb6EIlj7xs